baseURL: https://hamza-tam.gitlab.io/ensias-doc/
languageCode: en-us
title: ENSIAS Wiki
theme: custom-cupper

taxonomies:
  tag: tags
  club: clubs

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Tutorials
      url: /post/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: Clubs
      url: /clubs/
      weight: 4
